FROM debian:trixie
LABEL maintainer="michalis@mpi-sws.org"

WORKDIR /root

RUN export TERM='xterm-256color'

RUN apt-get update
RUN apt-get install -y -qq wget gnupg gnupg2 bc \
    autoconf make automake libffi-dev zlib1g-dev libedit-dev \
    libxml2-dev xz-utils g++ clang git bsdmainutils coreutils

RUN apt-get install -y -qq \
    clang-16  llvm-16   llvm-16-dev

# COPY fetch_deps.sh ./fetch_deps.sh
# RUN ./fetch_deps.sh
